# Generated by Django 4.2.4 on 2023-09-09 09:12

import django.core.exceptions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_remove_user_gender_profile_gender"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="first_name",),
        migrations.RemoveField(model_name="user", name="last_name",),
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                default="",
                max_length=254,
                unique=True,
                validators=[django.core.exceptions.ValidationError],
            ),
        ),
    ]
